import { APP_PLATFORM_CSP_RESOURCE_DOMAINS } from "@/services/apps/app-ui-policy";

// Authoring conventions for MCP Apps, lifted out of the tool descriptions so the
// scaffold/edit tools stay short. Exported for a later task that seeds them into
// an authoring skill; the CDN allowlist is derived from the policy that enforces
// it (APP_PLATFORM_CSP) so the two can never disagree.
/** @public — seeded into the MCP App authoring skill by a later task. */
export const APP_AUTHORING_CONTRACT = `Author PURE UI HTML against the Archestra Apps SDK the platform injects at render time as window.archestra — never import an SDK, read __ARCHESTRA_APP_SDK_URL__, or wire postMessage yourself (that glue is provided; hand-rolling it breaks the app). window.archestra exists synchronously; await archestra.ready (a promise) before the first call. Every archestra method below is async — await it; archestra.user is the one plain property:
- archestra.user — the authenticated viewer ({id, name}), readable synchronously after ready, so no login flow is needed.
- archestra.storage.user.{get,set,list,delete} (all async) persist state private to each viewer (favorites, drafts, settings — the right default); archestra.storage.shared.* is one store all viewers share. Values are plain JSON (top-level null is not storable; use delete to clear a key). get(key) resolves to an entry {value, revision, owner} or null when absent; list() resolves to [{key, value, revision, owner}] (NOT an array of keys) in no guaranteed order — sort client-side. set(key, value) resolves to {revision, owner}. For multi-user writes use optimistic concurrency: pass set(key, value, {ifRevision}) with the revision you last read — a stale write rejects with {code: "conflict"} (re-read and retry). set(key, value, {owned: true}) claims a new shared key for the viewer so only they (or the app's author/admins) may overwrite it; an unauthorized write rejects with {code: "forbidden"}. Generate ids for new records with crypto.randomUUID().
- archestra.tools.call(name, args) (async) calls an assigned tool as the viewing user with their credentials — pass name exactly as archestra.tools.list() returns it (the full assigned name, e.g. github__list_issues) — and it rejects with {code: "auth_required", url} when that tool's server still needs connecting (render the url as a link and let the user retry). archestra.tools.list() returns the assigned tools.
- archestra.llm.complete(prompt, {system, jsonMode}) (async) runs ONE host LLM completion as the viewer (using the org's configured model — the app cannot choose one) and resolves to the model's text; use it to summarize, classify, extract, or generate over data the app ALREADY HAS (tool results, stored values, user input). jsonMode steers the model to return a single JSON value you then JSON.parse. It rejects with {code: "llm_quota"} when usage limits are reached and {code: "llm_unavailable"} otherwise. archestra.llm.prompt\`...\` is a tagged-template helper that builds a prompt string (pure, no call). This is NOT a data source — it cannot fetch anything; the tools-only rule below still governs all external data.
- archestra.ui.openLink(url) and archestra.ui.requestDisplayMode(mode) reach the host; archestra.context is the running app's {appId, version} (a plain property, readable after ready).
TOOLS-ONLY DATA RULE: ALL external data must come through assigned MCP tools — find one with search_tools, assign it via the tools param, call it with archestra.tools.call. The sandbox blocks network access (connect-src 'none'): fetch/XHR/WebSocket to any external API WILL FAIL and there is no per-app CSP override. The one exception is static assets (scripts, styles, fonts, images) from the platform CDN allowlist (${APP_PLATFORM_CSP_RESOURCE_DOMAINS.join(", ")}) — use it for client-side libraries, never as a data channel. A platform stylesheet is also injected: style against its theme variables (e.g. --color-text-primary/-secondary, --color-background-primary/-secondary, --color-border-primary, --color-accent, --border-radius-md, --font-sans/-mono; light/dark aware) and its .arch-* components (.arch-card, .arch-btn with --primary/--ghost, .arch-input, .arch-badge, .arch-spinner, .arch-tabs) — write only app-specific CSS, never a full theme, and never <link> the platform stylesheet yourself.`;

// Authoring-loop guidance, honest about what is and isn't available outside the
// interactive chat surface (preview_app_tool needs human approval; render
// diagnostics only exist once a browser has rendered the app).
/** @public — seeded into the MCP App authoring skill by a later task. */
export const APP_BUILD_LOOP_GUIDANCE = `Tool-calling apps follow a fixed order: assign the tool (tools param on scaffold_app/edit_app), then — interactively — call preview_app_tool with the new app's id to observe the tool's real output shape before writing code that parses it (it needs human approval, and you cannot preview a tool that is not assigned yet, so scaffold the app first; a minimal scaffold is fine). In non-interactive contexts preview is unavailable — code defensively against the tool's documented schema instead. After scaffold/edit, call get_app_diagnostics to read the diagnostics from the most recent render of the current version (a render happens when the app is shown inline in chat or at its run page); if the current version has not been rendered yet it returns no_render_observed, and any runtime errors will instead arrive on the user's next message.`;
